### ISSUE TITLE
KNN issue cannot get the feature importance.

### ISSUE THREAD

**Issue by ashish620-boogle** [ashish620-boogle/Feature_Extraction_-_NLP_Classification_with_RFC#1]
Not able to get the feature importance values. Suggest a different algorithm that will do the work.

**Comment by RaghavSethi25** [comment]
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=42, max_depth=2, n_estimators=100)
clf.fit(X_train, y_train)


i think this part of code will help you to get the importance values

**Comment by ashish620-boogle** [comment]
Thanks. It works. Great job.
